name: "Pull Request Labeler"
on:
  pull_request:
    types: [closed]

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5

  comment_pr:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    name: Comment about the change log label
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Hello world and ${{ github.event.assignee.login }} @${{ github.event.assignee.login }} ${{ github.event.assignee.name }} @${{ github.event.assignee.name }} ! :wave:
            This PR has been closed and the `change log` label has been added.